import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/page";

// ------------------
// Metadata مع الفافيكون
// ------------------
export const metadata: Metadata = {
  title: "freshMart",
  description: "Generated by create next app",
  icons: {
    icon: "/public/marketshopping.ico",      // من public مباشرة
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="bg-zinc-50 text-zinc-900" cz-shortcut-listen="true">
        <Navbar />
        <main className="min-h-[calc(100vh-160px)]">
          <Toaster />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}